-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSxZi9BBhBnBQ4WP9
cbWdsF1/pVIECbBQFC0gyZLs9GmgCgYIKoZIzj0DAQehRANCAATeQXKqGe5nVKgO
wv6vWFdu5JZUQX6iCAG8cJhIjRzyFx5YXvf0wNiRipR1sLaSFkzczklNmyuzNAPO
A2vpm/oA
-----END PRIVATE KEY-----